cards_list = [
	"What is the formula for the CDS price?",
	"How to calculate one-period POD?",
	"Credit cycle? Four phase? Credit spread slope shape?",
	"Empircal duration v.s. Analytical duration?",
	"Seven fixed-rate bond's spreads?",
	"Yield-based measures (benchmark spread) = ? - ? √ × ？",
	"G-spread = ? - ? √ × ？",
	"I-spread = ? - ? √ × ？",
	"Asset swap spread (ASW) = ? - ? √ × ？",
	"Z-spread = ? - ? √ × ？",
	"CDS basis = ? - ? √ × ？",
	"Option adjusted spread (OAS) = ? - ? ✔ × ？",
	"Floating-rate bond's spreads?",
	"Z-DM consider what?",
	"Credit Strategies: Bottom-Up Top-Down?",
	"Credit Rating Categories: which two? W?O?",
	"Calculate VaR through 99% standard deviation?",
	"Using Asset Swaps to Manage Liquidity Risk?",
	"CDS Spread < Fixed Coupon: CDS premium or discount?",
	"Credit Spread Curves over the Economic Cycle?",
	"What is roll-down strategy?",
]